services:
  app:
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresDatabase:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=car123
    ports:
      - "8092:8091"
    depends_on:
      - postgresDatabase
    restart: unless-stopped

  postgresDatabase:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: car123
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    #    volumes:
    #      - db\
    #      - :/data/postgres
    ports:
      - "5432:5432"
    restart: always
#    restart: unless-stopped


#volumes:
#  db: /data/